export const userCont={
    LOGIN:"LOGIN",
    USERLIST:"USERLIST",
    EDITUSER:"EDITUSER",
    DELUSER:"DELUSER"
};
/*export const loadingCont= {
    LOADINGSTATE: "LOADINGSTATE"
};*/
export const SHOWNOTIFICATION="SHOWNOTIFICATION";
export const HIDENOTIFICATION="HIDENOTIFICATION";
export const streamCont={
    SEARCH_QUERY:"SEARCH_QUERY",
    STREAM_LIST:"STREAM_LIST",
    PACKAGE_QUERY_DATA:"PACKAGE_QUERY_DATA",
    PACKAGE_DATA:"PACKAGE_DATA",
    ONLINE_QUERY_DATA:"ONLINE_QUERY_DATA",
    ONLINE_DATA:"ONLINE_DATA"
}
export const channelCont={
    CHANNEL_DATA:"CHANNEL_DATA",
    CHANNEL_SEARCH_QUERY:"CHANNEL_SEARCH_QUERY",
    CHANNEL_LIST:"CHANNEL_LIST",
    CHANNEL_BIT_DATA:"CHANNEL_BIT_DATA",
    CHANNEL_BIT_QUERY:"CHANNEL_BIT_QUERY",
    CHANNEL_CODE_DATA:"CHANNEL_CODE_DATA",
    CHANNEL_CODE_QUERY:"CHANNEL_CODE_QUERY",
    CHANNEL_CODE_ISP:"CHANNEL_CODE_ISP",
    EDIT_CHANNEL_DEVICE:"EDIT_CHANNEL_DEVICE",
    CHANNEL_TOTAL_DATA:"CHANNEL_TOTAL_DATA",
    CHANNEL_TOTAL_QUERY:"CHANNEL_TOTAL_QUERY"

}
export const originCont={
    ORIGIN_DATA:"ORIGIN_DATA",
    ORIGIN_SEARCH_QUERY:"ORIGIN_SEARCH_QUERY",
    ORIGIN_LIST:"ORIGIN_LIST",
    ORIGIN_CODE_DATA:"ORIGIN_CODE_DATA",
    ORIGIN_BIT_DATA:"ORIGIN_BIT_DATA",
    ORIGIN_SUB_BIT_DATA:"ORIGIN_SUB_BIT_DATA",
    ORIGIN_SUB_CODE_DATA:"ORIGIN_SUB_CODE_DATA"

}

